### ISSUE TITLE
Sign-In Page

### ISSUE THREAD

**Issue by farouk26** [202306-NEA-DZ-FEW/team-a#30]
**Description:**
Create a sign-in page with a form component using the reusable InputField, Formik, and Yup for validation. Illustrate the page design as closely as possible to the Figma file. At the end, console log the form data for testing.

**Subtasks:**

 

- [ ] Design and create the Sign-In page.
- [ ]  Implement the Sign-In form using the reusable InputField, from Formik, and Yup.
- [ ]  Illustrate the page design closely to the Figma file.
- [ ]  Add functionality to console log the form data on submission.

**Areas of Acceptance:**

- [ ] The Sign-In page is created.
- [ ] The Sign-In form is functional with input validation.
- [ ] The page design closely matches the Figma file.
- [ ] Form data is correctly logged to the console upon submission.
