### ISSUE TITLE
Sign-Up Page

### ISSUE THREAD

**Issue by farouk26** [202306-NEA-DZ-FEW/team-a#31]
**Description:**
Create a sign-up page with a form component using the reusable InputField, Formik, and Yup for validation. Illustrate the page design as closely as possible to the Figma file. At the end, console log the form data for testing.

**Subtasks:**

- [x]  Design and create the Sign-Up page.
- [x]  Implement the Sign-Up form using the reusable InputField, from Formik, and Yup.
- [x]  Illustrate the page design closely to the Figma file.
- [x]  Add functionality to console log the form data on submission.
- [x] Default Language: The default language is set to English, and the entire page content is displayed in English by default.
- [x] Multi-Language Support: When users select a different language from the language selector , all textual content on the entire page is accurately translated into the chosen language.

**Areas of Acceptance:**

- [x] The Sign-Up page is created.
- [x] The Sign-Up form is functional with input validation.
- [x] The page design closely matches the Figma file.
- [x] Form data is correctly logged to the console upon submission.
- [x] Sign-Up page is fully functional with complete page content translations into different languages, offering a seamless multilingual user experience
- [ ] Code changes are reviewed and approved by the team.

**Screenshots**

- **Large Screen View**

![Screenshot 2023-10-17 155211](https://github.com/202306-NEA-DZ-FEW/team-a/assets/25696810/41cc36db-9365-46a4-bca1-0e45ed68baf9)
--------------------------------------------------------------------------------------------------------------------------------------------

- **Mobile View** 

![Screenshot 2023-10-17 225725](https://github.com/202306-NEA-DZ-FEW/team-a/assets/25696810/f0e983d3-9ae4-46c0-825c-e9ae11256555)
