### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by farouk26** [202306-NEA-DZ-FEW/team-a#32]
**Description:**
Create a user dashboard page with components for the user profile, a list of user items, and a reusable single item component.

**Subtasks:**

- [x]  Design and create the Dashboard page.
- [x]  Implement the User Profile component.
- [x]  Implement the List of User Items component.
- [x]  Create a reusable Single Item component.
- [x] Default Language: The default language is set to English, and the entire page content is displayed in English by default.
- [x] Multi-Language Support: When users select a different language from the language selector , all textual content on the entire page is accurately translated into the chosen language.

**Areas of Acceptance:**

- [x] The Dashboard page is created.
- [ ] User Profile, List of User Items, and Single Item components are functional.
- [x] Components are styled and illustrated as per the Figma file.
- [x] The Dashboard provides an overview of user information and items.
- [x] Dashboard page is fully functional with complete page content translations into different languages, offering a seamless multilingual user experience.
- [x] Code changes are reviewed and approved by the team.

**Screenshots** 

- **Large Screen View**

![Screenshot 2023-10-17 225644](https://github.com/202306-NEA-DZ-FEW/team-a/assets/25696810/7c6a6a12-97c6-4232-b4dc-5e915f5697fe)
--------------------------------------------------------------------------------------------------------------------------------------------

- **Mobile View**

![Screenshot 2023-10-17 225801](https://github.com/202306-NEA-DZ-FEW/team-a/assets/25696810/a09bac6f-e6c0-4ee4-9e5b-3e7bc4191a70)
