### ISSUE TITLE
Blogs Page

### ISSUE THREAD

**Issue by liliumorion** [202306-NEA-DZ-FEW/team-a#47]
**Create Blogs Page**

**Task:** Develop the "Blogs page" for the project which will serve as a platform to display all available blog posts.

**Objective:** Design the page that includes a preview for each blog with its title, overview, and a "read more" button.

**Subtasks:**

- [x] Design the layout for the Blogs Page, displaying blog post previews.
- [x] Each preview contains a title, a topic overview, an image related to the topic, and a "read more" button to access the blog.
- [x]  Implement functionality to fetch and display blog post informations from Firebase.

Areas of Acceptance:

- The Blogs page is created.
- The page design closely matches the Figma file and responsive.
- The "Blogs Page" displays a list of blog post previews.
- Blog post information is dynamically fetched and displayed.
- Code changes are reviewed and approved by the team.

Desktop view : 

![Image](https://user-images.githubusercontent.com/88900793/277747714-aab3e175-062e-4507-b093-9d3de4c0109a.png)

Mobile view: 

![Image](https://user-images.githubusercontent.com/88900793/277747885-da9ceb05-cf12-407b-aa43-fcfd1038b3ce.png)
