### ISSUE TITLE
Products Page

### ISSUE THREAD

**Issue by liliumorion** [202306-NEA-DZ-FEW/team-a#52]
**Issue: Create All Products Page with Filters**

**Description:**

This page should include product categories and filters to allow users to refine their search.

**Subtasks:**

- [x]  Design and create the "All items" page.
- [x]  Illustrate the page design closely to the Figma file.
- [ ]  Implement filtering options for categories, province, and title.
- [ ]  Connect the page to the database to fetch and display the relevant product listings based on the applied filters.

**Areas of Acceptance:**

- The "All products" page is created.
- The page design closely matches the Figma file.
- The "All Products" page is responsive, functional and displays product categories, filters and a preview of items.
- Users can apply filters to refine their search results.

After completing this issue, users should be able to browse and filter through the available products.

Desktop view: 

![Image](https://user-images.githubusercontent.com/88900793/278089533-ba6b6110-eb74-4d57-bb0a-c8b9f87c7243.png)

Mobile view: 

![Image](https://user-images.githubusercontent.com/88900793/278089674-87dc0cff-48e5-4e09-8c64-41a2bb0bd61a.png)
