### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by liliumorion** [202306-NEA-DZ-FEW/team-a#54]
**Issue: About Page Creation**

**Description:**

The About Page is an informational resource that offers insights into the platform's mission, and purpose, as well as the team members behind the website. 

**Subtasks:**

- [x] Design the About Page, including sections for the mission statement, team members, and the platform's purpose.
- [x] Add accurate and relevant information about the platform and goals.
- [x] Ensure the About Page is easily accessible from the navigation menu.
- [x] Add the necessary test file.

**Areas of Acceptance:**

- The About Page is created;
- the page provides clear and concise information about the platform's mission, purpose, and team members.
- the page design closely matches the Figma file.
- All information on the About Page is accurate and up-to-date.
- Users can easily navigate to the About Page from the navigation menu.

Desktop view: 

![Image](https://github.com/202306-NEA-DZ-FEW/team-a/assets/88900793/ae12a73b-f7e1-45b3-9cad-f517cbf05da1)

Mobile view:

![Image](https://github.com/202306-NEA-DZ-FEW/team-a/assets/88900793/b845d2b9-93ba-40b8-a7fd-f688a9339d4c)
