### ISSUE TITLE
Reusable Cover Section

### ISSUE THREAD

**Issue by liliumorion** [202306-NEA-DZ-FEW/team-a#55]
**Issue: Create a reusable Cover component** 

**Description:**

Create a reusablepage cover component that can be used in the "about " page and single blog page. 
this component should include the title, the description, and the background image.

**Subtasks:**

- [x] Create the reusable page cover component.
- [x] Ensure the component is accessible and responsive.
- [x] Create the appropriate test.

**Areas of Acceptance:**

-  The component is responsive and reusable.
-  Code changes are reviewed and approved by the team.
