### ISSUE TITLE
Create Missing Category

### ISSUE THREAD

**Issue by rahemSorour** [202306-NEA-DZ-FEW/team-a#79]
**Issue 1: Create Missing Category**

**Description:**

The task involves adding "clothes" category

**Subtasks:**

- [ ] Add the missing category
- [ ] Add the convenient translation to this category in the JSON files
- [ ] Ensure that the category is accessible in the navigation menu.
- [ ] Test the category's functionality to ensure it works as expected.

**Areas of Acceptance:**

- The missing category is successfully added to the website
- All relevant components and views display the new category.
- The category is accessible from the selection menu.
- The category functions correctly without any issues.
