### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by rahemSorour** [202306-NEA-DZ-FEW/team-a#82]
**Subtasks:**
- [x] Review each page of the website to identify all text that lacks translations.
- [x] Update the translation JSON files with the accurate translations for each key.
- [x] Update test files.

**Acceptance Criteria:**

- All content is fully translated into the supported languages.
- The translation preserves the same meaning in all three languages
