### ISSUE TITLE
Create Newsletter Section

### ISSUE THREAD

**Issue by liliumorion** [202306-NEA-DZ-FEW/team-a#85]
**Create Newsletter Section**

**Description:**

The task involves incorporating a "newsletter" section into the website.

**Subtasks:**

- [x] Integrate a dedicated "newsletter" section into the website.
- [x] Confirm that users can subscribe successfully and receive updates.
- [x] Create a "success" page once the visitor subscribes.
- [x] make both the newsletter section and success page responsive to desktop & mobile view.
- [x] Add test files.

**Areas of Acceptance:**

- The newsletter section is successfully incorporated, responsive & functional.
- All relevant components are rendered properly.
- Test files present and passed.
- The newsletter functionality operates without any glitches or issues.
- Users can receive updates.
