### ISSUE TITLE
Navbar and Footer Enhancements

### ISSUE THREAD

**Issue by riadhmouamnia** [202306-NEA-DZ-FEW/team-a#89]
## Issue 1: Navbar and Footer Enhancements

**Description:**
Enhance the visual appeal and functionality of the navbar and footer components for a more cohesive and user-friendly experience.

**Subtasks:**
1. **Fix Footer Language Menu:**
   - [ ]  Adjust the footer language menu to match the design and functionality of the navbar language menu.
   - [ ]  Make sure when the language is changed the page won't change.

2. **Add Dashboard Icon to Navbar:**
   - [ ] Include a missing dashboard icon next to the dashboard link in the user menu on the navbar.

3. **Navbar Position Adjustment:**
   - [ ] Replace the use of `sticky` with `fixed` class for the navbar position.
   - [ ] Review and resolve any layout issues on other pages that might be impacted by this change.
